export const T20Batters = [
    {
        id: 1,
        name: "Virat Kohli",
        matches: "115",
        innings: "107",
        runs: "4008",
        highestScore: "122*",
        average: "52.73",
        strikeRate: "137.96",
        centuries: "1",
        halfCenturies: "37",
        fours: "356",
        sixes: "117",
        wickets: "4",
    },
    {
        id: 2,
        name: "Rohit Sharma",
        matches: "148",
        innings: "140",
        runs: "3853",
        highestScore: "118",
        average: "31.32",
        strikeRate: "139.25",
        centuries: "4",
        halfCenturies: "29",
        fours: "354",
        sixes: "182",
        wickets: "1",
    },
    {
        id: 3,
        name: "Martin Guptill",
        matches: "122",
        innings: "118",
        runs: "3531",
        highestScore: "105",
        average: "31.81",
        strikeRate: "135.70",
        centuries: "2",
        halfCenturies: "20",
        fours: "311",
        sixes: "173",
        wickets: "3",
    },
    {
        id: 4,
        name: "Babar Azam",
        matches: "104",
        innings: "99",
        runs: "3485",
        highestScore: "122",
        average: "41.48",
        strikeRate: "128.41",
        centuries: "3",
        halfCenturies: "30",
        fours: "367",
        sixes: "55",
        wickets: "0",
    },
    {
        id: 5,
        name: "Paul Stirling",
        matches: "135",
        innings: "134",
        runs: "3561",
        highestScore: "115*",
        average: "28.84",
        strikeRate: "134.02",
        centuries: "1",
        halfCenturies: "23",
        fours: "344",
        sixes: "136",
        wickets: "20",
    },
    {
        id: 6,
        name: "Aaron Finch",
        matches: "103",
        innings: "100",
        runs: "3120",
        highestScore: "172",
        average: "34.28",
        strikeRate: "142.53",
        centuries: "2",
        halfCenturies: "19",
        fours: "311",
        sixes: "125",
        wickets: "0",
    },
    {
        id: 7,
        name: "David Warner",
        matches: "99",
        innings: "99",
        runs: "2894",
        highestScore: "100*",
        average: "32.88",
        strikeRate: "141.31",
        centuries: "1",
        halfCenturies: "24",
        fours: "284",
        sixes: "108",
        wickets: "0",
    },
    {
        id: 8,
        name: "Mohammad Rizwan",
        matches: "80",
        innings: "73",
        runs: "2635",
        highestScore: "104*",
        average: "48.82",
        strikeRate: "126.62",
        centuries: "1",
        halfCenturies: "23",
        fours: "229",
        sixes: "65",
        wickets: "0",
    },
    {
        id: 9,
        name: "Shoaib Malik",
        matches: "124",
        innings: "111",
        runs: "2435",
        highestScore: "75",
        average: "31.13",
        strikeRate: "125.64",
        centuries: "0",
        halfCenturies: "9",
        fours: "168",
        sixes: "61",
        wickets: "28",
    },
    {
        id: 10,
        name: "Eoin Morgan",
        matches: "115",
        innings: "107",
        runs: "2458",
        highestScore: "91",
        average: "28.58",
        strikeRate: "136.17",
        centuries: "0",
        halfCenturies: "14",
        fours: "198",
        sixes: "120",
        wickets: "10",
    }
];
