import { PlayerImage } from "@/types/playerImage";

export const TestBattersImage: PlayerImage[] = [
    {
        id: 1,
        image: "/srt.jpg", // Add image path or URL
        name: "Sachin Tendulkar",
        matches: 200,
        innings: 329,
        runs: 15921,
        highestScore: "248*",
        average: 53.78,
        strikeRate: 54.08,
        centuries: 51,
        halfCenturies: 68,
        fours: 2058,
        sixes: 69,
        wickets: 46,
    },
    {
        id: 2,
        image: "/rt.jpeg", // Add image path or URL
        name: "Ricky Ponting",
        matches: 168,
        innings: 287,
        runs: 13378,
        highestScore: "257",
        average: 51.85,
        strikeRate: 58.72,
        centuries: 41,
        halfCenturies: 62,
        fours: 1509,
        sixes: 73,
        wickets: 5,
    },
    {
        id: 3,
        image: "/jk.jpeg", // Add image path or URL
        name: "Jacques Kallis",
        matches: 166,
        innings: 280,
        runs: 13289,
        highestScore: "224",
        average: 55.37,
        strikeRate: 45.97,
        centuries: 45,
        halfCenturies: 58,
        fours: 1488,
        sixes: 97,
        wickets: 292,
    },
    {
        id: 4,
        image: "/rd.jpg", // Add image path or URL
        name: "Rahul Dravid",
        matches: 164,
        innings: 286,
        runs: 13288,
        highestScore: "270",
        average: 52.31,
        strikeRate: 42.51,
        centuries: 36,
        halfCenturies: 63,
        fours: 1654,
        sixes: 21,
        wickets: 1,
    },
    {
        id: 5,
        image: "/cook.jpeg", // Add image path or URL
        name: "Alastair Cook",
        matches: 161,
        innings: 291,
        runs: 12472,
        highestScore: "294",
        average: 45.35,
        strikeRate: 46.95,
        centuries: 33,
        halfCenturies: 57,
        fours: 1342,
        sixes: 11,
        wickets: 0,
    },
    {
        id: 6,
        image: "/ks.jpeg", // Add image path or URL
        name: "Kumar Sangakkara",
        matches: 134,
        innings: 233,
        runs: 12400,
        highestScore: "319",
        average: 57.40,
        strikeRate: 54.19,
        centuries: 38,
        halfCenturies: 52,
        fours: 1491,
        sixes: 51,
        wickets: 0,
    },
    {
        id: 7,
        image: "/bl.jpg", // Add image path or URL
        name: "Brian Lara",
        matches: 131,
        innings: 232,
        runs: 11953,
        highestScore: "400*",
        average: 52.88,
        strikeRate: 60.51,
        centuries: 34,
        halfCenturies: 48,
        fours: 1559,
        sixes: 88,
        wickets: 0,
    },
    {
        id: 8,
        image: "/chandrapaul.jpeg", // Add image path or URL
        name: "Shivnarine Chanderpaul",
        matches: 164,
        innings: 280,
        runs: 11867,
        highestScore: "203*",
        average: 51.37,
        strikeRate: 43.29,
        centuries: 30,
        halfCenturies: 66,
        fours: 1283,
        sixes: 38,
        wickets: 9,
    },
    {
        id: 9,
        image: "/mj.jpeg", // Add image path or URL
        name: "Mahela Jayawardene",
        matches: 149,
        innings: 252,
        runs: 11814,
        highestScore: "374",
        average: 49.84,
        strikeRate: 50.93,
        centuries: 34,
        halfCenturies: 50,
        fours: 1384,
        sixes: 61,
        wickets: 0,
    },
    {
        id: 10,
        image: "/border.jpeg", // Add image path or URL
        name: "Allan Border",
        matches: 156,
        innings: 265,
        runs: 11174,
        highestScore: "205",
        average: 50.56,
        strikeRate: 40.11,
        centuries: 27,
        halfCenturies: 63,
        fours: 1111,
        sixes: 39,
        wickets: 39,
    }
];
